version: '3.1'

services:
  api:
    build:
      dockerfile: api.Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  migrator:
    build:
      dockerfile: migrator.Dockerfile
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calc_db
      PGDATA: /var/lib/postgresql/data/
    ports:
      - "5442:5432"
    volumes:
      - postgres:/var/lib/postgresql/data/

volumes:
  postgres: