version: "3"

tasks:
  docker_dev:
    aliases:
      - dev
    desc: "Start development environment"
    cmds:
      - docker-compose -f docker-compose.dev.yml up -d
  migrate_down:
    aliases:
      - down
    desc: "Rollback migrations"
    cmds:
      - migrate -path ./migrations -database postgres://postgres:postgres@localhost:5442/game_db?sslmode=disable down
  migrate_up:
    aliases:
      - up
    desc: "Apply migrations"
    cmds:
      - migrate -path ./migrations -database postgres://postgres:postgres@localhost:5442/game_db?sslmode=disable up